server:
  port: 8761

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: auditevents, health, info, metrics, threaddump, heapdump, loggers, configprops

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/