spring:
  application:
    name: pizzaprovider

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: auditevents, health, info, metrics, threaddump, heapdump, loggers, configprops

# Run app with -Dserver.port=9081 as VM arguments
#server:
#  port: ${vcap.application.port:9081}

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/