spring:
  application:
    name: feignclient

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: auditevents, health, info, metrics, threaddump, heapdump, loggers

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

server:
  port: ${vcap.application.port:9091}

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/